# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0442d3307c469080dc7dfe0dd8166000593426ef0deb9cfb800c9579108f1df36232ad498a0ce1cd20308b720386c7351daade3bab4322ef68e0bd8bc4c4d0fe

test:
  secret_key_base: 99ba3eb724796014cbb0a89321994ae4325d55b9e7e78499885ecb70b4d71172bd5664eeeaf49dfbca93b8a68820da948591d74e9eea5c2fb91a940a7f27573f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
